### ISSUE TITLE
It's impossible for an end-user to set up this app

### ISSUE THREAD

**Issue by Bellfalasch** [enonic-archive/app-google-analytics-old#7]
Even though app can be installed via market, the app cannot be setup to work as a widget without developer assistanse.

Could installation process be simplified? Move some settings inside app? Any other ways to solve this?

https://github.com/enonic/app-google-analytics/blob/master/docs/installing.md

**Comment by alansemenov** [comment]
The goal of the installation is to set up service account and retrieve a file with token. No way to do this without going through setup in the GA console. 
The console UI keeps changing though and the installation guide is outdated. We'll fix it here: https://github.com/enonic/app-google-analytics/issues/10
